---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demos.james.com
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demos.james.com
  resources:
  - demoes/finalizers
  verbs:
  - update
- apiGroups:
  - demos.james.com
  resources:
  - demoes/status
  verbs:
  - get
  - patch
  - update
