apiVersion: demos.james.com/v1
kind: Demo
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo-sample
    app.kubernetes.io/part-of: k8s-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-crd
  name: demo-sample
spec:
  # TODO(user): Add fields here
